
INSERT INTO transactions (PurchaseOrderID, OrderQty, ProductID, UnitPrice, LineTotal)
VALUES
(1,4,1,50.04,23.04),
(2,3,13,98.09,46.08),
(2,3,345,88.04,99.99),
(3,550,112,22.01,63.77),
(4,3,453,33.44,48.09),
(5,550,154,55.02,100.11),
(6,550,334,33.98,88.99),
(7,550,554,55.98,33.99),
(7,550,23,122.09,77.99),
(7,550,90,69.02,178.33),
(8,3,88,12.08, 99.33),
(8,3,23,56.90,50.89),
(8,3,89,60.09,61.33),
(8,3,45,34.09,65.90),
(8,3,67,69.98,82.88),
(9,3,76,33.09,49.21),
(9,3,45,49.07,18.33),
(9,3,89,99.09,98.12),
(9,3,25,59.02,83.12),
(9,3,56,11.99,98.22),
(10,60,88,22.99,24.11),
(10,3,66,48.09,66.33),
(10,3,11,65.09,89.21),
(11,3,44,37.09,19.03),
(11,3,99,98.44,16.66),
(11,550,22,100.201,82.11),
(11,3,44,66.89,94.12),
(12,3,90,77.09,98.12),
(13,60,911,87.98,74.23),
(13,3,233,88.99,19.64),
(13,3,990,46.88,49.22),
(13,3,21,39.11,66.12),
(14,3,12,78.44,84.05),
(15,3,44,55.33,64.02);






 -- ('Quo velit iusto ducimus quos a incidunt nesciunt facilis.', 2, 4),
 --       ('Non est totam.', 5, 5),
        -- ('Fuga et iste beatae.', 3, 3),
        -- ('Molestias tempore est.', 1, 5),
        -- ('Est voluptatum voluptatem voluptatem est ullam quod quia in.', 1, 5),
        -- ('Aut et similique porro ullam.', 1, 3),
        -- ('Fugiat cupiditate consequatur sit magni at non ad omnis.', 1, 2),
        -- ('Accusantium illo maiores et sed maiores quod natus.', 2, 5),
        -- ('Perferendis cumque eligendi.', 1, 2),
        -- ('Nihil quo voluptatem placeat.', 5, 5),
        -- ('Rerum dolor sunt sint.', 5, 2),
        -- ('Id corrupti tenetur similique reprehenderit qui sint qui nulla tenetur.', 2, 1),
        -- ('Maiores quo quia.', 1, 5),
        -- ('Culpa perferendis qui perferendis eligendi officia neque ex.', 1, 4),
        -- ('Reprehenderit voluptates rerum qui veritatis ut.', 1, 1),
        -- ('Aut ipsum porro deserunt maiores sit.', 5, 3),
        -- ('Aut qui eum eos soluta pariatur.', 1, 1),
        -- ('Praesentium tempora rerum necessitatibus aut.', 4, 3),
        -- ('Magni error voluptas veniam ipsum enim.', 4, 2),
        -- ('Et maiores libero quod aliquam sit voluptas.', 2, 3),
        -- ('Eius ab occaecati quae eos aut enim rem.', 5, 4),
        -- ('Et sit occaecati.', 4, 3),
        -- ('Illum omnis et excepturi totam eum omnis.', 1, 5),
        -- ('Nemo nihil rerum alias vel.', 5, 1),
        -- ('Voluptas ab eius.', 5, 1),
        -- ('Dolor soluta quisquam voluptatibus delectus.', 3, 5),
        -- ('Consequatur neque beatae.', 4, 5),
        -- ('Aliquid vel voluptatem.', 4, 5),
        -- ('Maiores nulla ea non autem.', 4, 5),
        -- ('Enim doloremque delectus.', 1, 4),
        -- ('Facere vel assumenda.', 2, 5),
        -- ('Fugiat dignissimos dolorum iusto fugit voluptas et.', 2, 1),
        -- ('Sed cumque in et.', 1, 3),
        -- ('Doloribus temporibus hic eveniet temporibus corrupti et voluptatem et sint.', 5, 4),
        -- ('Quia dolorem officia explicabo quae.', 3, 1),
        -- ('Ullam ad laborum totam veniam.', 1, 2),
        -- ('Et rerum voluptas et corporis rem in hic.', 2, 3),
        -- ('Tempora quas facere.', 3, 1),
        -- ('Rem autem corporis earum necessitatibus dolores explicabo iste quo.', 5, 5),
        -- ('Animi aperiam repellendus in aut eum consequatur quos.', 1, 2),
        -- ('Enim esse magni.', 4, 3),
        -- ('Saepe cumque qui pariatur.', 4, 4),
        -- ('Sit dolorem ipsam nisi.', 4, 1),
        -- ('Dolorem veniam nisi quidem.', 2, 5),
        -- ('Porro illum perferendis nemo libero voluptatibus vel.', 3, 3),
        -- ('Dicta enim rerum culpa a quo molestiae nam repudiandae at.', 2, 4),
        -- ('Consequatur magnam autem voluptas deserunt.', 5, 1),
        -- ('Incidunt cum delectus sunt tenetur et.', 4, 3),
        -- ('Non vel eveniet sed molestiae tempora.', 2, 1),
        -- ('Ad placeat repellat et veniam ea asperiores.', 5, 1),
        -- ('Eum aut magni sint.', 3, 1),
        -- ('Aperiam voluptates quis velit explicabo ipsam vero eum.', 1, 3),
        -- ('Error nesciunt blanditiis quae quis et tempora velit repellat sint.', 2, 4),
        -- ('Blanditiis saepe dolorem enim eos sed ea.', 1, 2),
        -- ('Ab veritatis est.', 2, 2),
        -- ('Vitae voluptatem voluptates vel nam.', 3, 1),
        -- ('Neque aspernatur est non ad vitae nisi ut nobis enim.', 4, 3),
        -- ('Debitis ut amet.', 4, 2),
        -- ('Pariatur beatae nihil cum molestiae provident vel.', 4, 4),
        -- ('Aperiam sunt aliquam illum impedit.', 1, 4),
        -- ('Aut laudantium necessitatibus harum eaque.', 5, 3),
        -- ('Debitis voluptatum nesciunt quisquam voluptatibus fugiat nostrum sed dolore quasi.', 3, 2),
        -- ('Praesentium velit voluptatem distinctio ut voluptatum at aut.', 2, 2),
        -- ('Voluptates nihil voluptatum quia maiores dolorum molestias occaecati.', 1, 4),
        -- ('Quisquam modi labore.', 3, 2),
        -- ('Fugit quia perferendis magni doloremque dicta officia dignissimos ut necessitatibus.', 1, 4),
        -- ('Tempora ipsam aut placeat ducimus ut exercitationem quis provident.', 5, 3),
        -- ('Expedita ducimus cum quibusdam.', 5, 1),
        -- ('In voluptates doloribus aut ut libero possimus adipisci iste.', 3, 2),
        -- ('Sit qui est sed accusantium quidem id voluptatum id.', 1, 5),
        -- ('Libero eius quo consequatur laudantium reiciendis reiciendis aliquid nemo.', 1, 2),
        -- ('Officia qui reprehenderit ut accusamus qui voluptatum at.', 2, 2),
        -- ('Ad similique quo.', 4, 1),
        -- ('Commodi culpa aut nobis qui illum deserunt reiciendis.', 2, 3),
        -- ('Tenetur quam aut rerum doloribus est ipsa autem.', 4, 2),
        -- ('Est accusamus aut nisi sit aut id non natus assumenda.', 2, 4),
        -- ('Et sit et vel quos recusandae quo qui.', 1, 3),
        -- ('Velit nihil voluptatem et sed.', 4, 4),
        -- ('Sunt vitae expedita fugiat occaecati.', 1, 3),
        -- ('Consequatur quod et ipsam in dolorem.', 4, 2),
        -- ('Magnam voluptatum molestias vitae voluptatibus beatae nostrum sunt.', 3, 5),
        -- ('Alias praesentium ut voluptatem alias praesentium tempora voluptas debitis.', 2, 5),
        -- ('Ipsam cumque aut consectetur mollitia vel quod voluptates provident suscipit.', 3, 5),
        -- ('Ad dignissimos quia aut commodi vel ut nisi.', 3, 3),
        -- ('Fugit ut architecto doloremque neque quis.', 4, 5),
        -- ('Repudiandae et voluptas aut in excepturi.', 5, 3),
        -- ('Aperiam voluptatem animi.', 5, 1),
        -- ('Et mollitia vel soluta fugiat.', 4, 1),
        -- ('Ut nemo voluptas voluptatem voluptas.', 5, 2),
        -- ('At aut quidem voluptatibus rem.', 5, 1),
        -- ('Temporibus voluptates iure fuga alias minus eius.', 2, 3),
        -- ('Non autem laboriosam consectetur officiis aut excepturi nobis commodi.', 4, 3),
        -- ('Esse voluptatem sed deserunt ipsum eaque maxime rerum qui.', 5, 5),
        -- ('Debitis ipsam ut pariatur molestiae ut qui aut reiciendis.', 4, 4),
        -- ('Illo atque nihil et quod consequatur neque pariatur delectus.', 3, 3),
        -- ('Qui et hic accusantium odio quis necessitatibus et magni.', 4, 2),
        -- ('Debitis repellendus inventore omnis est facere aliquam.', 3, 3),
        -- ('Occaecati eos possimus deleniti itaque aliquam accusamus.', 3, 4),
        -- ('Molestiae officia architecto eius nesciunt.', 5, 4),
        -- ('Minima dolorem reiciendis excepturi culpa sapiente eos deserunt ut.', 3, 3);