
INSERT INTO Product (ProductID, ProductName, Color)
VALUES
(1,"laptop","red"),
(13,"juice", "red"),
(345,"sandwich","red"),
(112,"fruit","red"),
(453,"toy","red"),
(154,"phone","red"),
(334,"mouse","red"),
(554,"piano","red"),
(23,"pencil","red"),
(90,"pen","red"),
(88,"chord","red"),
(23,"tv","red"),
(89,"rubber","red"),
(45,"grillers","red"),
(67,"tshirt","blue"),
(76,"pan cake","blue"),
(45,"chewing gum","blue"),
(89,"eclaire","blue"),
(25,"book","blue"),
(56,"piano","blue"),
(88,"bottle","blue"),
(66,"violin","blue"),
(11,"saxsaphone","blue"),
(44,"mouse","blue"),
(99,"door","blue"),
(22,"car","blue"),
(44,"trousers","blue"),
(90,"notebook","blue"),
(911,"worksheets","blue"),
(233,"ipad","blue"),
(990,"newspaper","blue"),
(21,"book shelf","blue"),
(12,"coach","blue"),
(44,"dress","blue");

